/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary': '#002e6a',
        'on-primary-fixed': '#001a42',
        'on-tertiary-container': '#00311f',
        'outline-variant': '#424754',
        'tertiary': '#4edea3',
        'secondary-container': '#00a6e0',
        'surface-container-high': '#1c2b3c',
        'on-surface-variant': '#c2c6d6',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#004395',
        'surface-dim': '#051424',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#005236',
        'surface': '#051424',
        'surface-container': '#122131',
        'error-container': '#93000a',
        'surface-container-low': '#0d1c2d',
        'secondary-fixed': '#c4e7ff',
        'on-tertiary-fixed': '#002113',
        'inverse-on-surface': '#233143',
        'on-secondary-container': '#00374d',
        'on-tertiary': '#003824',
        'on-background': '#d4e4fa',
        'surface-container-highest': '#273647',
        'primary-fixed-dim': '#adc6ff',
        'surface-bright': '#2c3a4c',
        'primary-container': '#4d8eff',
        'secondary': '#7bd0ff',
        'on-primary-container': '#00285d',
        'surface-container-lowest': '#010f1f',
        'surface-lowest': '#010f1f',
        'on-surface': '#d4e4fa',
        'outline': '#8c909f',
        'on-secondary-fixed': '#001e2c',
        'inverse-surface': '#d4e4fa',
        'error': '#ef4444',
        'background': '#051424',
        'primary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-fixed-variant': '#004c69',
        'tertiary-container': '#00a572',
        'surface-variant': '#273647',
        'primary': '#adc6ff',
        'secondary-fixed-dim': '#7bd0ff',
        'on-secondary': '#00354a',
        'tertiary-fixed': '#6ffbbe',
        'inverse-primary': '#005ac2',
        'surface-tint': '#adc6ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'gutter': '1rem',
        'space-xs': '0.25rem',
        'space-xl': '2rem',
        'margin': '1rem',
        'margin-desktop': '1.5rem',
        'gutter-desktop': '1.5rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'label-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'display-lg-mobile': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'headline-md': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'data-tabular': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-sm': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'display-lg': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg': ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        sans: ['var(--font-inter)', 'Inter', 'sans-serif'],
        display: ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'display-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'data-tabular': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      animation: {
        'ping-slow': 'ping-slow 2.4s cubic-bezier(0, 0, 0.2, 1) infinite',
        'radar-pulse': 'radar-pulse 3s infinite ease-in-out',
      },
      keyframes: {
        'ping-slow': {
          '0%': { transform: 'scale(1)', opacity: '0.8' },
          '50%': { transform: 'scale(1.6)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '0' },
        },
        'radar-pulse': {
          '0%': { transform: 'scale(0.95)', opacity: '0.8' },
          '50%': { transform: 'scale(1.3)', opacity: '0.2' },
          '100%': { transform: 'scale(0.95)', opacity: '0.8' },
        },
      },
    },
  },
  plugins: [],
};
